# Generated by Django 3.2.4 on 2021-06-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_alter_playlist_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
    ]
