# Generated by Django 3.2.4 on 2021-06-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0009_tvshowproxy_tvshowseasonproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv show', 'TV Show'), ('season', 'Season'), ('playlist', 'Playlist')], default='playlist', max_length=8),
        ),
    ]
