# Generated by Django 3.2.4 on 2021-06-21 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'All Videos'},
        ),
    ]
